config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  resources :users, except: [:new, :edit, :destroy, :update]
  resource :session, only: [:create, :destroy]
  resources :chats, except: [:new, :edit, :destroy] do
    resources :messages, only: [:create, :index]
    member do
      post 'readall'
    end
  end

  root 'main#index'

end

app/models/chat.rb
class Chat < ActiveRecord::Base
  has_many :messages
  has_many :chat_items
  has_many :users, through: :chat_items, validate: false

  validates :name, presence: true, uniqueness: true, length: { in: 1..20 }

  before_save :check_min_users_count

  def unread_messages_count(user)
    chat_items.find_by(user: user).try :unread_messages_count
  end

  private

  def check_min_users_count
    if users.size > 1
      return true
    else
      errors.add(:base, 'minimum 2 users')
      return false
    end
  end
end

app/models/chat_item.rb
class ChatItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :chat
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :chat

  validates :text, presence: true, length: { minimum: 1 }
  validates :user, presence: true
  validates :chat, presence: true

  before_create :check_that_user_from_chat
  after_create :inc_unread_messages

  def user_name
    user.name
  end

  def create_time
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end

  private

  def inc_unread_messages
    ChatItem.where(chat: chat).where.not(user: user)
      .update_all 'unread_messages_count = unread_messages_count + 1'
  end

  def check_that_user_from_chat
    if chat.users.include? user
      return true
    else
      errors.add(:base, 'user not in chat')
      return false
    end
  end
end

app/models/user.rb
# require 'bcrypt'

class User < ActiveRecord::Base
  # include BCrypt

  has_many :messages
  has_many :chat_items
  has_many :chats, through: :chat_items

  validates :name, presence: true, uniqueness: true, length: { in: 3..20 }

  has_secure_password
  validates :password, length: { minimum: 6 }
  # def password
  #   @password ||= Password.new(password_hash)
  # end

  # def password=(new_password)
  #   @password = Password.create(new_password)
  #   self.password_hash = @password
  # end

  def messages_count
    messages.count
  end

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  respond_to :json

  def index
    @chats = current_user.chats
  end

  def show
    @chat = Chat.find(params[:id])
  end

  def create
    @chat = Chat.new(name: chat_params[:name])
    @chat.users << User.find(chat_params[:user_ids].split(',').map(&:to_i)).uniq
    @chat.users << current_user unless @chat.users.include? current_user
    if @chat.save
      render :show
    else
      render json: {}, status: 500
    end
  end

  def update
    chat = Chat.find(params[:id])
    chat.user_ids = chat_params[:user_ids].split(',').map(&:to_i).to_a.push(current_user.id).uniq
    chat.name = chat_params[:name]
    render json: {}, status: chat.save ? 200 : 500
  end

  def readall
    ci = ChatItem.find_by(chat_id: params[:id], user: current_user)
    ci.unread_messages_count = 0
    render json: {}, status: ci.save ? 200 : 500
  end

  private

  def chat_params
    params.require(:chat).permit(:name, :user_ids)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  respond_to :json

  def create
    chat = Chat.find(params[:chat_id])
    if current_user.chats.include? chat
      @message = Message.new(text: message_params[:text], user: current_user, chat: chat)
      if @message.save
        render :show
      else
        render json: {}, status: 500
      end
    else
      render json: {}, status: 500
    end
  end

  def index
    chat = Chat.find(params[:chat_id])
    @messages = chat.messages.last chat.unread_messages_count(current_user)
  end

  private

  def message_params
    params.require(:message).permit(:text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  respond_to :json

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user && @user.authenticate(params[:session][:password])
      sign_in @user
      render template: 'users/show'
    else
      render json: {}, status: 500
    end
  end

  def destroy
    sign_out
    render json: {}, status: 200
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json

  def index
    @users = User.all
  end

  def show
    @users = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      render :show
    else
      render json: { error: @user.errors.full_messages }, status: 500
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    if signed_in?
      current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
      cookies.delete(:remember_token)
      self.current_user = nil
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MlsChat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">

    <div class="row">
      <%= yield %>
    </div>

    <div class="row">
      <hr/>
      <div class="footer" id="footer">
        <p> &copy; Belkot Oleh 2016
      </div>
    </div>

  </div>

</body>
</html>

app/views/main/index.html.haml
#signout
  User
  %span#userName
  = link_to 'Sign out', session_path, method: :delete, remote: true, id: 'signout_link'

.row
  .col-md-3
    .panel.panel-default
      .panel-heading Chats:
      .list-group#chatsList

    #accordionChat.panel-group{'aria-multiselectable' => 'true', :role => 'tablist'}

      .panel.panel-default
        #headingChatCreate.panel-heading{:role => 'tab'}
          %h4.panel-title
            %a{'aria-controls' => 'collapseChatCreate', 'aria-expanded' => 'true', 'data-parent' => '#accordionChat', 'data-toggle' => 'collapse', :href => '#collapseChatCreate', :role => 'button'}
              Create:

        #collapseChatCreate.panel-collapse.collapse.in{'aria-labelledby' => 'headingChatCreate', :role => 'tabpanel'}
          .panel-body
            = simple_form_for(:chat, url: chats_path(format: :json), format: :json, remote: true) do |f|
              .form-inputs
                = f.input :name, required: true
                = f.input :user_ids, required: true
              .formatorm-actions
                = f.button :submit, 'Create'

      .panel.panel-default
        #headingChatUpdate.panel-heading{:role => 'tab'}
          %h4.panel-title
            %a.collapsed{'aria-controls' => 'collapseChatUpdate', 'aria-expanded' => 'false', 'data-parent' => '#accordionChat', 'data-toggle' => 'collapse', :href => '#collapseChatUpdate', :role => 'button'}
              Update:
        #collapseChatUpdate.panel-collapse.collapse{'aria-labelledby' => 'headingChatUpdate', :role => 'tabpanel'}
          .panel-body
            = simple_form_for(:chat, url: chat_path(action: :update, id: 0, format: :json), format: :json, remote: true, method: :put, html: { id: 'chatUpdateForm'}) do |f|
              .form-inputs
                = f.input :name, required: true
                = f.input :user_ids, required: true
              .formatorm-actions
                = f.button :submit, 'Update'

  .col-md-6
    .panel.panel-default
      .panel-heading#chatName Chatname
      .panel-body#chatBody
      .panel-footer
        = simple_form_for(:message, url: chat_messages_path(chat_id: 0, format: :json), html: { id: 'messageForm'}, format: :json, remote: true ) do |f|
          / = f.error_notification
          .form-inputs
            = f.input :text, required: true, autofocus: true, label: false, as: :text, input_html: {rows: 5, style: 'resize: none' }
          .form-actions
            = f.button :submit, 'Send'
            = link_to 'Mark all as read', '/chat/0/readall.json', remote: true, method: :post, class: 'btn btn-default', id: 'markReadAll'

  .col-md-3
    #accordionUsers.panel-group{'aria-multiselectable' => 'true', :role => 'tablist'}

      .panel.panel-default
        #headingUserInChat.panel-heading{:role => 'tab'}
          %h4.panel-title
            %a{'aria-controls' => 'collapseUserInChat', 'aria-expanded' => 'true', 'data-parent' => '#accordionUsers', 'data-toggle' => 'collapse', :href => '#collapseUserInChat', :role => 'button'}
              Users in chat:
        #collapseUserInChat.panel-collapse.collapse.in{'aria-labelledby' => 'headingUserInChat', :role => 'tabpanel'}
          .panel-body

      .panel.panel-default
        #headingUserAll.panel-heading{:role => 'tab'}
          %h4.panel-title
            %a.collapsed{'aria-controls' => 'collapseUserAll', 'aria-expanded' => 'false', 'data-parent' => '#accordionUsers', 'data-toggle' => 'collapse', :href => '#collapseUserAll', :role => 'button'}
              All users:
        #collapseUserAll.panel-collapse.collapse{'aria-labelledby' => 'headingUserAll', :role => 'tabpanel'}
          .panel-body

#signModal.modal.fade{:role => 'dialog'}
  .modal-dialog
    .modal-content
      .modal-body
        / %button.close{'data-dismiss' => 'modal', :type => 'button'} ×
        #signTab
          %ul.nav.nav-tabs.nav-justified
            %li.active{:role => 'presentation'}
              %a{'data-toggle' => 'tab', :href => '#signin'} Sign in
            %li{:role => 'presentation'}
              %a{'data-toggle' => 'tab', :href => '#signup'} Sign up
        .tab-content
          #signup.tab-pane.fade
            / %h2 Sign up
            = simple_form_for(:user, url: users_path(format: :json), html: { id: 'signup_form' }, format: :json, remote: true) do |f|
              = f.error_notification
              .form-inputs
                = f.input :name, required: true, autofocus: true
                = f.input :password, required: true
                = f.input :password_confirmation, required: true
              .form-actions
                = f.button :submit, 'Sign up'

          #signin.tab-pane.fade.in.active
            / %h2 Sign in
            = simple_form_for(:session, url: session_path(format: :json) ,html: { id: 'signin_form' }, format: :json, remote: true) do |f|
              = f.error_notification
              .form-inputs
                = f.input :name, required: true, autofocus: true
                = f.input :password, required: true
              .form-actions
                = f.button :submit, 'Sign in'